kind: Pod
apiVersion: v1
metadata:
  name: server-go
  labels:
    app: server-go
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
    - name: server-go
      image: server-go
      imagePullPolicy: Never
      ports:
        - containerPort: 4343
          protocol: TCP
          name: grpc
---
kind: Service
apiVersion: v1
metadata:
  name: server-go
spec:
  selector:
    app: server-go
  ports:
    - port: 8080
      appProtocol: kubernetes.io/h2c
      protocol: TCP
      targetPort: 4343
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: server-go
  namespace: default
  annotations:
    retry.linkerd.io/grpc: unavailable,resource-exhausted
    retry.linkerd.io/limit: "5"
spec:
  parentRefs:
    - name: server-go
      group: ""
      kind: Service
      port: 8080
  rules:
    - matches:
        - method:
            service: connectrpc.eliza.v1.ElizaService
            method: Say
            type: Exact
      backendRefs:
        - kind: Service
          name: server-go
          port: 8080
